Added data viz notebook
marinadunn/SHIFT-STAC-demo pull request #1
Opened 2022-04-28 02:40 UTC by dieumynguyen

2022-04-28 19:06 UTC, marinadunn requested changes

2022-04-28 19:06 UTC, marinadunn commented on data_visualization_demo.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAmYAAABzCAYAAAAyqM6LAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAD1ZklEQVR4nOz
Just to clarify, this bounding box is the larger box the extent falls into and is based on exterior coords, correct? 

When you define this, did you manually pick out points to use? If so, can we implement something to make this translatable to other datasets? I have an example of getting the bbox from the extent if needed.

2022-04-28 19:06 UTC, marinadunn commented on data_visualization_demo.ipynb
> +   "source": [
Let's remove lines 11-192, aka the first block since we won't need to install packages individually

2022-04-28 19:06 UTC, marinadunn commented on data_visualization_demo.ipynb
> +    "import cartopy.feature as cfeature"
Helpful for ignoring warnings:
import warnings
warnings.filterwarnings('ignore')

2022-04-28 19:06 UTC, marinadunn commented on data_visualization_demo.ipynb
> +    "Red = ds.sel(wavelength=665, method='nearest').Reflectance\n",
I think we had been using 670nm for best red band

2022-04-28 19:06 UTC, marinadunn commented on data_visualization_demo.ipynb
> +    "RGB = ds.sel(wavelength=[665,550,440], method='nearest').Reflectance"
Same here for 670. We can also divide RGB by 0.7 to lighten up the image to see better.

2022-04-28 19:06 UTC, marinadunn commented on data_visualization_demo.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAmYAAABzCAYAAAAyqM6LAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAD1ZklEQVR4nOz
Same here for 670.

2022-04-28 19:06 UTC, marinadunn commented on data_visualization_demo.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAmYAAABzCAYAAAAyqM6LAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAD1ZklEQVR4nOz
Same here for 670.

2022-04-28 19:06 UTC, marinadunn commented on data_visualization_demo.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAmYAAABzCAYAAAAyqM6LAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAD1ZklEQVR4nOz
Same here for 670.

2022-04-28 23:20 UTC, dieumynguyen reviewed
Made the changes you suggested. Let me know if there's anything else to add.

2022-04-28 23:20 UTC, dieumynguyen commented on data_visualization_demo.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAmYAAABzCAYAAAAyqM6LAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAD1ZklEQVR4nOz
What bounding box are you referring to? The one defined by `box_minx`, `box_maxx`, `box_miny`, and `box_maxy`? If so, this is not the bounding box of the entire image as you've previously calculated, but just a small box representing an arbitrary rectangular region we want to subset. The points defining this box are manually picked, just as a user can pick any rectangle (or polygon, as shown in the methods that work below) they want from the data.

2022-04-29 18:36 UTC, marinadunn approved these changes

2022-04-29 18:36 UTC, marinadunn approved these changes

2022-04-29 18:37 UTC, merged